### ISSUE TITLE
Inconsistent version number at "Installing" wiki page

### ISSUE THREAD

**Issue by fangfufu** [keyleds/keyleds#61]
For the Debian instruction, this line: 
```
curl -sL https://github.com/keyleds/keyleds/archive/v1.1.0.tar.gz|tar xzf -

```
the ``v1.1.0`` should be replaced with ``v1.1.1`` to ensure the consistency, so the end user can copy and paste the command. This is really minor. I would give you a pull request if I could, but it seems that I cannot clone the wiki and edit it myself.

**Comment by spectras** [comment]
Thanks, fixed!
